name: horizon_platform
version: 1.0.0
config-version: 2

profile: horizon_platform

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  horizon_platform:
    marts:
      +materialized: view
      +schema: dbt_marts

vars:
  bigquery_dataset: job_market_analysis
